name: Continuous Deployment

on:
  release:
    types:
      - created

jobs:
  deploy:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - name: Publish
        if: startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
        run: vsce publish --yarn -p ${{ secrets.VSCE_PAT }}
